# Generated by Django 5.2.17 on 2026-08-20 20:32

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(max_length=255, unique=True)),
                ('fingerprint', models.CharField(max_length=255)),
                ('materialized_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('engine', models.CharField(default='ollama', max_length=64)),
                ('endpoint', models.CharField(max_length=512)),
                ('model_id', models.CharField(max_length=255)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('embed_dim', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_modelconnection_name_ci')],
            },
        ),
        migrations.CreateModel(
            name='RoleBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(max_length=255)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_bindings', to='inference.modelconnection')),
            ],
            options={
                'ordering': ['role_key'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('role_key'), name='uniq_rolebinding_role_key_ci')],
            },
        ),
    ]
