# Generated by Django 5.2.4 on 2026-08-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0002_seed_from_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconnection',
            name='context_window',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
