# Generated by Django 5.2.4 on 2026-08-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0003_modelconnection_context_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconnection',
            name='descriptor',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='modelconnection',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
