# Generated by Django 5.2.17 on 2026-08-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0004_modelconnection_descriptor_modelconnection_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconnection',
            name='embed_dim',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
