# Generated by Django 5.2.17 on 2026-08-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0005_alter_modelconnection_embed_dim'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconnection',
            name='footprint_override_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelconnection',
            name='measured_footprint_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelconnection',
            name='measured_footprint_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
