# Generated by Django 5.2.17 on 2026-08-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0006_modelconnection_footprint_override_bytes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconnection',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
