# Generated by Django 5.2.4 on 2026-08-31 23:17

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """`ModelSet`, `ModelSetMember`, `ModelSetEntitlement` -- the three
    tables behind the 2026-08-30 owner directives (spec sections 22.31
    and 22.33): models group into named SETS, and an entitlement attaches
    to a set rather than to a connection directly, "so one change can
    impact many different entitlements/users".
    """

    dependencies = [
        ('identity', '0003_entitlement_and_grant'),
        ('inference', '0007_modelconnection_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_sets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModelSetEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('attached_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_set_attachments', to='identity.entitlement')),
                ('model_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_attachments', to='inference.modelset')),
            ],
        ),
        migrations.CreateModel(
            name='ModelSetMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_memberships', to='inference.modelconnection')),
                ('model_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='inference.modelset')),
            ],
        ),
        migrations.AddConstraint(
            model_name='modelset',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_modelset_name_ci'),
        ),
        migrations.AddIndex(
            model_name='modelsetentitlement',
            index=models.Index(fields=['entitlement'], name='inference_setent_ent'),
        ),
        migrations.AddConstraint(
            model_name='modelsetentitlement',
            constraint=models.UniqueConstraint(fields=('model_set', 'entitlement'), name='uniq_modelset_entitlement'),
        ),
        migrations.AddIndex(
            model_name='modelsetmember',
            index=models.Index(fields=['connection'], name='inference_setmember_conn'),
        ),
        migrations.AddConstraint(
            model_name='modelsetmember',
            constraint=models.UniqueConstraint(fields=('model_set', 'connection'), name='uniq_modelset_member'),
        ),
    ]
