# Generated by Django 5.2.4 on 2026-09-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0008_modelset'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconnection',
            name='engine_reported_footprint_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelconnection',
            name='engine_reported_footprint_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
