# Generated by Django 5.2.17 on 2026-08-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_budget_bytes', models.BigIntegerField(blank=True, null=True)),
                ('max_concurrent_jobs', models.PositiveIntegerField(default=4)),
                ('default_priority', models.PositiveIntegerField(default=100)),
                ('retention_limit', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='InferenceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('priority', models.PositiveIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.CharField(blank=True, default='', max_length=64)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('exclusive', models.BooleanField(default=False)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('model_refs', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['state', 'priority', 'id'], name='jobs_claim_scan'), models.Index(fields=['state', 'heartbeat_at'], name='jobs_orphan_sweep')],
            },
        ),
    ]
