# Generated by Django 5.2.4 on 2026-08-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencejob',
            name='checkpoint',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='progress',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
