# Generated by Django 5.2.17 on 2026-09-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_inferencejob_progress_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsettings',
            name='max_queued_per_principal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
