# Generated by Django 5.2.17 on 2026-09-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobsettings_max_queued_per_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsettings',
            name='response_timeout_seconds',
            field=models.PositiveIntegerField(default=1800),
        ),
    ]
