# Generated by Django 5.2.4 on 2026-09-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobsettings_response_timeout_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencejob',
            name='not_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='passed_over',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobsettings',
            name='detected_memory_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobsettings',
            name='detected_memory_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobsettings',
            name='kind_wait_seconds',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='inferencejob',
            index=models.Index(fields=['state', 'not_before', 'priority', 'id'], name='jobs_claim_scan_holdoff'),
        ),
    ]
