# Generated by Django 5.2.4 on 2026-08-27 20:58

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('llm_role', models.CharField(default='chat.converse', max_length=255)),
                ('tool_keys', models.JSONField(blank=True, default=list)),
                ('max_steps', models.PositiveIntegerField(default=8)),
                ('resident', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='uniq_agent_slug_ci')],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('owner_kind', models.CharField(blank=True, default='', max_length=32)),
                ('owner_key', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='agents.agent')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_kind', models.CharField(max_length=32)),
                ('principal_key', models.CharField(max_length=255)),
                ('tool_key', models.CharField(db_index=True, max_length=255)),
                ('args', models.JSONField(blank=True, default=dict)),
                ('outcome', models.CharField(choices=[('ok', 'OK'), ('refused', 'Refused'), ('param_error', 'Bad arguments'), ('error', 'Error'), ('degraded', 'Degraded')], max_length=16)),
                ('text', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['principal_kind', 'principal_key'], name='agents_inv_principal')],
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool'), ('system', 'System')], max_length=16)),
                ('text', models.TextField(blank=True, default='')),
                ('tool_call', models.JSONField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('artifacts', models.JSONField(blank=True, default=list)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='done', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('queue_job_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='agents.conversation')),
                ('invocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='agents.toolinvocation')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['owner_kind', 'owner_key'], name='agents_conv_owner'),
        ),
        migrations.AddIndex(
            model_name='turn',
            index=models.Index(fields=['conversation', 'index'], name='agents_turn_thread'),
        ),
        migrations.AddConstraint(
            model_name='turn',
            constraint=models.UniqueConstraint(fields=('conversation', 'index'), name='uniq_turn_index'),
        ),
    ]
