# Generated by Django 5.2.4 on 2026-08-28 14:33

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('inputs', models.JSONField(blank=True, default=list)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('resident', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('owner_kind', models.CharField(blank=True, default='', max_length=32)),
                ('owner_key', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='owner_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='owner_kind',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='toolinvocation',
            name='queue_job_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['owner_kind', 'owner_key'], name='agents_agent_owner'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['owner_kind', 'owner_key'], name='agents_flow_owner'),
        ),
        migrations.AddConstraint(
            model_name='flow',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='uniq_flow_slug_ci'),
        ),
    ]
