# Generated by Django 5.2.4 on 2026-08-31 03:05
"""IA-2's agents migration: tool labels and shares.

The repository's SECOND cross-app migration dependency (the first is
`identity/migrations/0003_entitlement_and_grant.py`): `ToolEntitlement.
entitlement` is a string FK to `"identity.Entitlement"`, so this
migration depends on `identity`'s 0003 as well as on `swappable_
dependency(settings.AUTH_USER_MODEL)` for the several user FKs and on
`("auth", "__first__")` for `Share.group` -- pinned to auth's FIRST
migration (where `Group` is created), not whatever migration happens to
be auth's current leaf, for the same reason identity's 0003 gives:
`Group` has not changed shape since, and a leaf pin would make this
migration's history depend on which contrib migrations happen to exist
in the Django version installed at generation time.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_flow_owners_and_invocation_job'),
        ('auth', '__first__'),
        ('identity', '0003_entitlement_and_grant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='toolinvocation',
            name='agent_slug',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('conversation', 'Conversation'), ('agent', 'Agent'), ('flow', 'Flow'), ('vision_output', 'Generated image')], max_length=16)),
                ('target_key', models.CharField(max_length=64)),
                ('level', models.CharField(choices=[('view', 'Can view'), ('use', 'Can use')], default='view', max_length=8)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to='auth.group')),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['target_type', 'target_key'], name='agents_share_target'), models.Index(fields=['user'], name='agents_share_user'), models.Index(fields=['group'], name='agents_share_group')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('user__isnull', False)), models.Q(('group__isnull', False), ('user__isnull', True)), _connector='OR'), name='share_user_xor_group'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('target_type', 'target_key', 'user'), name='uniq_share_target_user'), models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('target_type', 'target_key', 'group'), name='uniq_share_target_group')],
            },
        ),
        migrations.CreateModel(
            name='ToolEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_key', models.CharField(max_length=255)),
                ('labelled_at', models.DateTimeField(auto_now_add=True)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_labels', to='identity.entitlement')),
                ('labelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tool_key'], name='agents_toollabel_key')],
                'constraints': [models.UniqueConstraint(fields=('tool_key', 'entitlement'), name='uniq_tool_entitlement')],
            },
        ),
    ]
