# Generated by Django 5.2.4 on 2026-09-01 01:17
"""`AgentEntitlement` and `FlowEntitlement` (spec section 6.11, Task 15).

A SECOND `agents` MIGRATION, NOT AN EDIT TO `0003_toolentitlement_and_
share`: that migration is already designed and another task depends on
it, and rewriting a numbered migration to save a file is exactly what
Django's migration numbering exists to avoid.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_toolentitlement_and_share'),
        ('identity', '0003_entitlement_and_grant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelled_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_labels', to='agents.agent')),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_labels', to='identity.entitlement')),
                ('labelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entitlement'], name='agents_agentlabel_ent')],
                'constraints': [models.UniqueConstraint(fields=('agent', 'entitlement'), name='uniq_agent_entitlement')],
            },
        ),
        migrations.CreateModel(
            name='FlowEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelled_at', models.DateTimeField(auto_now_add=True)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_labels', to='identity.entitlement')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_labels', to='agents.flow')),
                ('labelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entitlement'], name='agents_flowlabel_ent')],
                'constraints': [models.UniqueConstraint(fields=('flow', 'entitlement'), name='uniq_flow_entitlement')],
            },
        ),
    ]
