# Generated by Django 5.2.4 on 2026-09-02
"""`Conversation.archived_at` -- the chat sidebar's archive (UI-3b).

ONE COLUMN, NULLABLE, NO DEFAULT ROW REWRITE: every existing
conversation is active, and `null` already says so, so this migration
adds a column and touches no data.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agent_flow_entitlements'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='archived_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
