# Generated by Django 5.2.4 on 2026-09-04, hand-arranged (see docstring below).

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """`Workstream` and its wall table (`WorkstreamScopeEntitlement`),
    `Conversation.workstream`, and `Share`'s fifth target.

    HAND-ARRANGED, NOT THE RAW AUTODETECTOR OUTPUT. Django's autodetector
    sorts newly-added models in REVERSE alphabetical order within one
    app (`swappable_first_key`, `reverse=True`) -- so, unprompted, it
    schedules `WorkstreamScopeEntitlement` for creation before
    `Workstream`, then has to defer ALL THREE of its foreign keys
    (`entitlement`, `set_by`, `workstream`) to separate `AddField`
    operations after `Workstream` exists, even though two of those three
    reference tables (`identity_entitlement`, the user table) that were
    already there. That split changes nothing about the resulting
    schema -- it is exactly the mechanical inverse of what follows, just
    less readable -- so it is undone here: `Workstream` is created
    first, `WorkstreamScopeEntitlement` second with all three of its
    foreign keys inline, and the five operations below are the complete,
    literal list. No data migration: `workstream` is nullable and every
    existing conversation is loose.
    """

    dependencies = [
        ('agents', '0005_conversation_archived_at'),
        ('identity', '0003_entitlement_and_grant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workstream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('instructions', models.TextField(blank=True, default='')),
                ('default_upload_placement', models.CharField(blank=True, choices=[('universal', 'The universal library'), ('contained', 'This workstream only')], default='', max_length=16)),
                ('owner_kind', models.CharField(blank=True, default='', max_length=32)),
                ('owner_key', models.CharField(blank=True, default='', max_length=200)),
                ('archived_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner_kind', 'owner_key'], name='agents_ws_owner')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('owner_kind'), models.F('owner_key'), name='uniq_workstream_name_ci_per_owner')],
            },
        ),
        migrations.CreateModel(
            name='WorkstreamScopeEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_at', models.DateTimeField(auto_now_add=True)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstream_scopes', to='identity.entitlement')),
                ('workstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_entitlements', to='agents.workstream')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entitlement'], name='agents_wsscope_ent')],
                'constraints': [models.UniqueConstraint(fields=('workstream', 'entitlement'), name='uniq_workstream_scope')],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='workstream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='agents.workstream'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['workstream', '-updated_at'], name='agents_conv_ws'),
        ),
        migrations.AlterField(
            model_name='share',
            name='target_type',
            field=models.CharField(choices=[('conversation', 'Conversation'), ('agent', 'Agent'), ('flow', 'Flow'), ('vision_output', 'Generated image'), ('workstream', 'Workstream')], max_length=16),
        ),
    ]
