# Generated by Django 5.2.4 on 2026-09-05 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_workstream'),
        ('identity', '0003_entitlement_and_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='consolidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='consolidated_through_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConversationTaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_turn', models.BigIntegerField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taint_tags', to='agents.conversation')),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_taints', to='identity.entitlement')),
            ],
            options={
                'indexes': [models.Index(fields=['entitlement'], name='agents_convtaint_ent')],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'entitlement'), name='uniq_conversation_taint')],
            },
        ),
        migrations.CreateModel(
            name='WorkstreamTaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_conversation', models.UUIDField(blank=True, null=True)),
                ('first_turn', models.BigIntegerField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstream_taints', to='identity.entitlement')),
                ('workstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taint_tags', to='agents.workstream')),
            ],
            options={
                'indexes': [models.Index(fields=['entitlement'], name='agents_wstaint_ent')],
                'constraints': [models.UniqueConstraint(fields=('workstream', 'entitlement'), name='uniq_workstream_taint')],
            },
        ),
    ]
