# Generated by Django 5.2.4 on 2026-09-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_workstream_taint'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstream',
            name='include_universal',
            field=models.BooleanField(default=True),
        ),
    ]
