# Generated by Django 5.2.4 on 2026-09-09
"""`Conversation.pinned_at` -- the chat sidebar's PINNED section (round
20, owner feedback: "can we add the ability t[o] pin chats so it's
always shown in its own se[c]tion... between Workstreams and Chats").

ONE COLUMN, NULLABLE, NO DEFAULT ROW REWRITE, the identical shape
`0005_conversation_archived_at.py` already used for `archived_at`:
every existing conversation is unpinned, and `null` already says so, so
this migration adds a column and touches no data.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_workstream_include_universal'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pinned_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
