# Generated by Django 5.2.4 on 2026-09-09
"""`ChatSettings` -- the chat column's operator-policy singleton (round
21, owner feedback: "can we inject the date/time into the prompt so
that its time aware ... This should also be configurable in the
settings but defaulted to on").

ONE TABLE, ONE MEANINGFUL COLUMN, NO SEED ROW. `ChatSettings.get_solo`
creates `pk=1` with defaults on first use -- the identical shape
`identity.models.IdentitySettings` and `tools.rag.models.RagSettings`
already use, and the reason a data migration would be dead weight here:
a box restored from a backup taken before this table existed gets the
same row, with the same owner-chosen default (time awareness ON), the
first time anything asks for it.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_conversation_pinned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_aware', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
