"""The identity column's founding migration: `User`, `IdentitySettings`
and `AuditEvent`, and nothing else.

IA-1 ships exactly FOUR migrations in this app. This is the first: it
must land in the same commit as `AUTH_USER_MODEL = "identity.User"` and
`"identity"` joining `INSTALLED_APPS`, or Django refuses to start (a
project cannot run with `AUTH_USER_MODEL` pointing at a model that has
no table yet).

No `swappable_dependency` on `AUTH_USER_MODEL`: `AuditEvent` carries no
foreign key to `User` by design (see `identity/models.py`), and `User`
is the swappable model itself, so nothing here needs to depend on its
own setting. `dependencies` below names the concrete `auth` migration
that `AbstractUser`'s inherited `groups`/`user_permissions` many-to-many
fields point at (`auth.Group`, `auth.Permission`) -- Django's
autodetector resolved that to the specific migration those models were
last altered in, not `("auth", "__first__")`, because a FK/M2M
dependency pins the migration that guarantees the referenced table's
current shape. `contenttypes` needs no dependency at all: nothing this
migration creates has a foreign key to `ContentType`.
"""
# Generated by Django 5.2.4 on 2026-08-30 03:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posture', models.CharField(choices=[('open', 'Open — no accounts, no login'), ('personal', 'Personal — a few local accounts, every one an administrator'), ('enterprise', 'Organisation — accounts, groups and entitlements')], default='open', max_length=16)),
                ('library_posture', models.CharField(choices=[('open', 'Open — an unlabelled document is readable by everyone signed in'), ('locked', 'Locked — an unlabelled document is readable by administrators only')], default='open', max_length=16)),
                ('admin_sees_content', models.BooleanField(default=False)),
                ('session_idle_minutes', models.PositiveIntegerField(default=720)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_kind', models.CharField(max_length=32)),
                ('actor_key', models.CharField(max_length=255)),
                ('actor_label', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_key', models.CharField(blank=True, default='', max_length=255)),
                ('target_label', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('web', 'Web page'), ('cli', 'Command line'), ('admin', 'Django admin')], default='web', max_length=16)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['actor_kind', 'actor_key'], name='identity_audit_actor'), models.Index(fields=['target_type', 'target_key'], name='identity_audit_target')],
            },
        ),
    ]
