# Generated by Django 5.2.4 on 2026-08-31 01:51
"""IA-2's identity migration: the named permission and who holds it.

The repository's FIRST cross-app migration dependency lives here
(`swappable_dependency` for the user FK, `("auth", "__first__")` for the
group FK). Before this, `docs/superpowers/specs/2026-08-25-*` could
record as a fact that the tree had neither; ADR 0016 records the
retirement of that fact.
"""

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # The User foreign keys (created_by, user, granted_by), named
        # explicitly via swappable_dependency rather than left implicit.
        # Functionally it resolves to identity's own first migration
        # (identity.User IS the swappable model, and this migration
        # lives in identity's own app), which the concrete dependency
        # on 0002 immediately below already implies -- but naming it
        # keeps this migration's dependency LIST self-documenting rather
        # than requiring a reader to know that same-app chaining is
        # silently doing the same job, and keeps this migration in the
        # same shape as 0003's siblings in other apps (migrations 8
        # and 9), where swappable_dependency is not redundant at all.
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # The ordinary same-app chain. Required regardless of the above:
        # dropping it would leave 0002 and 0003 as two sibling leaves of
        # identity's first migration, which is a conflicting-migrations
        # state Django refuses to apply.
        ('identity', '0002_repoint_admin_log_fk'),
        # The Group foreign key: a genuine cross-app dependency, pinned
        # to auth's FIRST migration (where Group is created) rather than
        # whatever migration happens to be auth's current leaf -- Group
        # has not changed shape since, and a leaf pin would make this
        # migration's history depend on which contrib migrations happen
        # to exist in the Django version installed at generation time.
        ('auth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EntitlementGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('owner', 'Owner')], default='member', max_length=8)),
                ('source', models.CharField(choices=[('manual', 'Granted here'), ('sso', 'From the identity provider')], default='manual', max_length=8)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='identity.entitlement')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants_made', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_grants', to='auth.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['entitlement__name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_entitlement_name_ci'),
        ),
        migrations.AddIndex(
            model_name='entitlementgrant',
            index=models.Index(fields=['user'], name='identity_grant_user'),
        ),
        migrations.AddIndex(
            model_name='entitlementgrant',
            index=models.Index(fields=['group'], name='identity_grant_group'),
        ),
        migrations.AddConstraint(
            model_name='entitlementgrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('user__isnull', False)), models.Q(('group__isnull', False), ('user__isnull', True)), _connector='OR'), name='grant_user_xor_group'),
        ),
        migrations.AddConstraint(
            model_name='entitlementgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('entitlement', 'user'), name='uniq_grant_entitlement_user'),
        ),
        migrations.AddConstraint(
            model_name='entitlementgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('entitlement', 'group'), name='uniq_grant_entitlement_group'),
        ),
    ]
