# Generated by Django 5.2.17 on 2026-09-21 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_entitlement_and_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitysettings',
            name='audit_detail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identitysettings',
            name='queue_retention_days',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='identitysettings',
            name='retention_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.CreateModel(
            name='DeletionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('key', models.CharField(max_length=200)),
                ('owner_kind', models.CharField(blank=True, default='', max_length=32)),
                ('owner_key', models.CharField(blank=True, default='', max_length=200)),
                ('deleted_by_kind', models.CharField(blank=True, default='', max_length=32)),
                ('deleted_by_key', models.CharField(blank=True, default='', max_length=200)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('purge_on', models.DateField(db_index=True)),
                ('hold_by_kind', models.CharField(blank=True, default='', max_length=32)),
                ('hold_by_key', models.CharField(blank=True, default='', max_length=200)),
                ('hold_note', models.TextField(blank=True, default='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='identity.deletionticket')),
                ('content_unrecoverable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['owner_kind', 'owner_key'], name='identity_ticket_owner')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'key'), name='uniq_deletion_ticket')],
            },
        ),
    ]
