# Generated by Django 5.2.17 on 2026-08-23 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=64)),
                ('params', models.JSONField(default=dict)),
                ('seed', models.BigIntegerField()),
                ('engine', models.CharField(max_length=64)),
                ('model_id', models.CharField(max_length=255)),
                ('model_fingerprint', models.CharField(max_length=255)),
                ('model_config', models.JSONField(blank=True, default=dict)),
                ('engine_ref', models.CharField(blank=True, max_length=255)),
                ('engine_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0)),
                ('path', models.CharField(max_length=1024)),
                ('media_type', models.CharField(blank=True, max_length=128)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='vision.generationjob')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='JobInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_key', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=1024)),
                ('media_type', models.CharField(blank=True, max_length=128)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='vision.generationjob')),
            ],
            options={
                'ordering': ['param_key'],
            },
        ),
    ]
