"""`seed` becomes nullable -- an operation may legitimately have no seed
(upscaling is deterministic) -- and the two `GenerationJob` indexes every
listing surface sorts or filters on (B8)."""
# Generated by Django 5.2.17 on 2026-08-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0002_generationjob_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationjob',
            name='seed',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='generationjob',
            index=models.Index(fields=['-created_at'], name='vision_job_created_idx'),
        ),
        migrations.AddIndex(
            model_name='generationjob',
            index=models.Index(fields=['status'], name='vision_job_status_idx'),
        ),
    ]
