# Generated by Django 5.2.17 on 2026-08-24 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0003_upscale_seed_and_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='failure_kind',
            field=models.CharField(blank=True, choices=[('params_invalid', 'Parameters invalid'), ('role_unbound', 'No image model assigned'), ('engine_unreachable', 'Image engine unreachable'), ('engine_rejected', 'Image engine refused the job'), ('engine_failed', 'Image engine failed the job'), ('lost', 'Image engine forgot the job')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='queue_job_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='jobinput',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobinput',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='vision.generationjob'),
        ),
    ]
