# Generated by Django 5.2.17 on 2026-08-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0004_queue_correlation_failure_kind_staged_inputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationjob',
            name='failure_kind',
            field=models.CharField(blank=True, choices=[('params_invalid', 'Parameters invalid'), ('role_unbound', 'No image model assigned'), ('connection_unavailable', 'Picked model no longer available'), ('engine_unreachable', 'Image engine unreachable'), ('engine_rejected', 'Image engine refused the job'), ('engine_failed', 'Image engine failed the job'), ('lost', 'Image engine forgot the job')], default='', max_length=32),
        ),
    ]
