# Generated by Django 5.2.4 on 2026-08-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0005_alter_generationjob_failure_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='owner_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='owner_kind',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='generationjob',
            index=models.Index(fields=['owner_kind', 'owner_key'], name='vision_job_owner'),
        ),
    ]
