# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0006_generationjob_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
