"""
DB-backed binding provider -- `models.registry.bindings.db_provider`, and
its pk-addressed twin `resolve_connection`.

`db_provider` is the "db" half of `models.contracts.bindings.resolve()`'s db ->
env fallback chain (see that module's docstring), and the default
`settings.INFERENCE_BINDING_PROVIDER` (Ruling 2). It answers "which
`ModelConnection` is bound to this role right now?" from the console's own
tables (`models.registry.models`); when it has no opinion -- no binding
row, an unbound (`connection=None`) binding, or the tables not existing yet
(mid-`migrate`, before this app's own migrations have run) -- it returns
`None` and `resolve()` falls back to `env_provider`, so an operator who
pinned a role from the environment (`LLM_MODEL`/`EMBED_MODEL`) still
resolves with no DB rows at all. With neither a binding row nor an explicit
environment override, `resolve()` raises and the role is honestly
unassigned -- there is no baked default to land on (ADR 0010 third
amendment).

`resolve_connection` answers a different question: "resolve THIS specific,
operator-chosen `ModelConnection` (by pk), for this capability" -- the seam
a caller-supplied override (e.g. the Ask-time model picker) resolves
through, independent of whatever role binding is currently durable. Unlike
`db_provider` it does not degrade to `None`; a pk that doesn't resolve to a
usable connection is a caller error, so it raises the same `ValueError`
`models.contracts.bindings.resolve()` and `models.contracts.engines.get_engine()`
already raise for "nothing usable here" -- there is no second exception type
for the same kind of failure.

Both providers build their `ResolvedModel` through the single
`resolved_from_connection()` helper below, so the field-by-field
construction (in particular, the `context_window`-only-when-set rule) can
never drift between the role-keyed and pk-keyed paths.

A few small reads live alongside `resolve_connection`, all for a per-request
model picker and its "answered by" / "generated by" line rather than for
resolution itself: `connections_for_picker(capability)` (the general
picker's option list -- `ModelConnection.objects.picker_order()` filtered
in Python to capability membership; `chat_connections_for_picker()` is now
a thin wrapper over it, kept as tools/rag's original name), `role_primary
(role_key)` (which connection -- or explicit environment override --
currently answers `role_key`, so a picker can mark/preselect it and a job
can name it on the un-overridden path once it actually finishes;
`answer_role_primary()` is a thin wrapper over it for
`models.contracts.roles.RAG_ANSWER_ROLE`, kept for the same reason). Both
generalized forms exist because `tools/vision` is now a second caller of
this same picker surface, alongside tools/rag -- one picker-option rule
and one role-primary rule, not a second copy per module. And
`resolve_connection_named()` (the same pk-addressed resolution
as `resolve_connection`, paired with the connection's display name in the
one query, for the overridden path -- avoiding a separate bare-name lookup
that would re-query the same row `resolve_connection` had just fetched). This
file is each §5 module's ONE console-side import surface for its picker
feature -- tools/rag (Ask-time) and now tools/vision reach here, never
into `models.registry.models` directly.

`footprint_for()` is a different kind of small read: not for the Ask
picker at all, but THE single path from a model ref (engine, endpoint,
model_id) to a memory footprint -- the execution queue's future claim code
never reads `ModelConnection.effective_footprint_bytes` directly, only
through this function, so there is exactly one place that "what does this
model cost to hold in memory" question is answered.

`record_measured_footprint()` is `footprint_for()`'s write-side twin (T4):
the worker's post-execution measurement writes `measured_footprint_bytes`/
`measured_footprint_at` through here, using the EXACT SAME match rule
(engine exact, endpoint `norm_endpoint`-normalized on both sides, model_id
exact) so a measurement can only ever land on the one row `footprint_for`
would itself have resolved for that same ref -- never a different row an
independently-written match rule might disagree with. Both it and its
rung-3 twin `record_engine_reported_footprint()` (spec §3.1) now go
through one shared writer, `_record_footprint`, which KEEPS THE MAXIMUM
(spec §3.2): a reading below the column's own standing value is refused
outright -- neither the bytes nor the timestamp are written -- rather
than tolerated within a band, because two live incidents show a
percentage band ratchets a standing value down over repeated warm runs
instead of preventing exactly that.

Imports are lazy and local to each function on purpose: Django's app
registry / DB access must not happen at import time (this keeps
`apps.py::ready()` and module import light, and matches
`models.contracts.bindings.resolve()`'s own lazy, per-call provider import).
"""
from __future__ import annotations

import logging
from typing import TYPE_CHECKING

logger = logging.getLogger(__name__)

# Below this ratio, a refused lowering is an OPERATOR-ACTIONABLE event
# (WARNING) rather than a note (INFO): a reading under three quarters of
# the standing value is the shape both live incidents took (26.4 -> 6.4
# GB, 15.2 -> 11.1 GB), and the operator's remedy -- set
# `footprint_override_bytes` -- is named in the line itself. A smaller dip
# is ordinary measurement noise and is recorded at INFO, so the refusal is
# still visible without teaching an operator to ignore warnings.
#
# A THRESHOLD FOR LOG LEVEL ONLY. No reading below the standing value is
# ever written, at any ratio: a tolerance band measured against the
# standing value ratchets geometrically and reproduces the exact incident
# this rule exists to refuse (spec §3.2).
FOOTPRINT_DIP_WARNING_RATIO = 0.75

# RE-EXPORTED, not re-implemented. `bindings` is the one submodule of this
# package every other column may import (the import-law gate names it by
# path), so the model-access question has to be reachable here or a caller
# would have to break that rule to ask it.
from models.registry.access import (  # noqa: F401 -- re-exported on purpose
    MODEL_FORBIDDEN_MESSAGE, UNRESTRICTED_MODEL_ACCESS, ModelAccess, model_access_for,
)

if TYPE_CHECKING:
    from models.registry.models import ModelConnection
    from models.contracts.bindings import ResolvedModel


def resolved_from_connection(connection: "ModelConnection") -> "ResolvedModel":
    """Build the `ResolvedModel` for `connection` -- the ONE construction
    path shared by `db_provider` (role-keyed) and `resolve_connection`
    (pk-keyed), so there is never a second copy of this mapping to drift
    out of sync with the first.

    `context_window` is an optional per-connection override (owner "nothing
    hidden" ruling): unset (None/0, blank in the edit form) means no
    opinion, so it is left out of `config` entirely and
    `models.contracts.engines.ollama.build_llm`'s own bounded
    `DEFAULT_CONTEXT_WINDOW` applies via `cfg.setdefault`. A set value rides
    through as an explicit `Ollama(context_window=...)` kwarg.

The connection's own `config` JSONField seeds that same dict, so an
    engine builder receives its per-connection extras (a multi-file
    checkpoint family naming its companion files, say) splatted as
    `**ResolvedModel.config`. Null in the DB means `{}` -- builders always
    get a mapping, never `None`. `context_window` is applied AFTER, so the
    dedicated column stays authoritative over any stray key of the same
    name in the JSON blob.

    Dedicated columns are the source of truth; a key in `config` matching a
    dedicated field's name is shadowed, never merged. (Cross-session
    agreement with the vision track, 2026-08-23.)
    """
    from models.contracts.bindings import ResolvedModel

    config: dict = dict(connection.config or {})
    if connection.context_window:
        config["context_window"] = connection.context_window
    return ResolvedModel(
        engine=connection.engine,
        model_id=connection.model_id,
        endpoint=connection.endpoint,
        embed_dim=connection.embed_dim,
        config=config,
    )


def db_provider(role_key: str) -> ResolvedModel | None:
    """Resolve `role_key` from `RoleBinding`/`ModelConnection`, or None.

    Returns `None` (never raises) for: no matching `RoleBinding` row, a
    binding whose `connection` is null (e.g. after the bound
    `ModelConnection` was deleted -- `SET_NULL`), or a `ProgrammingError`/
    `OperationalError` from the underlying table not existing yet -- all of
    which `_bound_connection` below already resolves to `None` for.
    """
    connection = _bound_connection(role_key)
    return resolved_from_connection(connection) if connection is not None else None


def connections_for_picker(capability: str) -> list["ModelConnection"]:
    """Registered connections answering `capability`, in picker order -- the
    option source for EVERY per-request model picker there is.

    Reuses `ModelConnection.objects.picker_order()` unmodified, filtered in
    Python on capability MEMBERSHIP (never `capabilities[0]`: a connection
    stores its model's full reported capability list, so one model can
    honestly belong in two pickers). This is the same filter idiom
    `models/registry/views.py::_role_options` already uses per role,
    rather than a second sort/filter rule.

    One function, not one per capability, because the rule is the same one
    and a second copy is a second thing to drift.
    """
    from models.registry.models import ModelConnection

    return [
        connection
        for connection in ModelConnection.objects.picker_order()
        if capability in connection.capabilities
    ]


def chat_connections_for_picker() -> list["ModelConnection"]:
    """Chat-capable registered connections -- the Ask-time picker's option
    source, and tools/rag's original name for it. A thin wrapper over
    `connections_for_picker` so the two pickers cannot drift apart on what
    "in picker order, filtered to a capability" means.
    """
    return connections_for_picker("chat")


def _bound_connection(role_key: str) -> "ModelConnection | None":
    """The `ModelConnection` currently bound to `role_key`'s `RoleBinding`,
    or `None` (no binding row, a null-connection binding, or the tables not
    migrated yet). Shared by `db_provider` (which wraps the connection, if
    any, in a `ResolvedModel`) and `answer_role_primary`, below, which needs
    the connection's own identity (pk, name) instead.
    """
    from django.db import OperationalError, ProgrammingError

    from models.registry.models import RoleBinding

    try:
        binding = (
            RoleBinding.objects.select_related("connection")
            .filter(role_key__iexact=role_key, connection__isnull=False)
            .first()
        )
    except (ProgrammingError, OperationalError):
        return None

    return binding.connection if binding else None


def role_primary(role_key: str) -> tuple[str, int | None]:
    """`(display_name, connection_pk)` for whatever currently answers
    `role_key` -- what a per-request model picker marks "(primary)" and
    preselects, and what a job's "answered by" / "generated by" line names on
    the un-overridden path.

    Three cases:
    - a `ModelConnection` is bound: `(connection.name, connection.pk)`.
    - no connection bound, but an explicit environment override resolves
      the role: `(f"{model_id} (environment override)", None)` -- there is
      no registry row to carry a pk, so a picker renders this as a
      synthetic, blank-value option instead of a pk-valued one. Only the
      two roles `env_provider` knows can ever reach this case; every other
      role falls through to the third.
    - neither: `("", None)` -- the role is genuinely unassigned.
    """
    from models.contracts.bindings import env_provider

    connection = _bound_connection(role_key)
    if connection is not None:
        return connection.name, connection.pk

    try:
        override = env_provider(role_key)
    except Exception:  # noqa: BLE001 -- an unresolvable override just means no primary
        override = None
    if override is not None:
        return f"{override.model_id} (environment override)", None

    return "", None


def answer_role_primary() -> tuple[str, int | None]:
    """`role_primary` for `models.contracts.roles.RAG_ANSWER_ROLE` --
    tools/rag's original name for it, kept so that module's one console
    import surface is unchanged."""
    from models.contracts.roles import RAG_ANSWER_ROLE

    return role_primary(RAG_ANSWER_ROLE)


def picker_options(capability: str, role_key: str, selected: str = "", *,
                   access: ModelAccess) -> list[dict] | None:
    """The per-request model picker's `<select>` options, in picker order,
    for any capability/role pair -- final-review finding 8. Lifted out of
    two near-identical copies, `tools.rag.views._connection_picker_
    options` (the Ask page's) and `tools.vision.views.
    _connection_picker_options` (the create page's), which built this same
    loop for their own capability/role.

    Options come from `connections_for_picker(capability)` with labels
    `{name} — {descriptor}` (bare `{name}` when undescribed). Whichever
    connection -- or explicit environment override -- currently answers
    `role_key` (`role_primary`) is preselected and gets " (primary)"
    appended, UNLESS `selected` names a different value: a re-render
    around an invalid submission (the create page's own re-render) must
    keep what the operator chose rather than silently reverting to the
    primary. `selected=""` (the default, and the Ask page's only caller)
    always selects the primary -- vision's own prior default behaviour.

    An env-override primary with no connection bound gets a synthetic
    first option (`value=""`) -- there is no registry row to point a
    pk-style value at; picking it (or leaving it default, i.e. `selected`
    still blank) means "use the role path", same as sending no
    `connection` at all.

    `None` -- no `<select>` at all -- only when there is nothing to pick
    from: no registered connection for `capability` and no environment
    override for `role_key`. A lone option still renders as a (trivial)
    select rather than collapsing to plain text.
    """
    primary_name, primary_pk = role_primary(role_key)
    connections = connections_for_picker(capability)
    # THE RENDER HALF, and it is free: a connection this principal may not
    # use is never in the `<select>`, so no page has to render-gate a
    # model option separately from the rule that refuses it.
    connections = [c for c in connections if access.allows(c.pk)]

    if not connections and not primary_name:
        return None

    options = []
    if primary_pk is None and primary_name:
        options.append({"value": "", "label": primary_name, "selected": not selected})

    for connection in connections:
        label = (
            f"{connection.name} — {connection.descriptor}"
            if connection.descriptor
            else connection.name
        )
        is_primary = connection.pk == primary_pk
        if is_primary:
            label = f"{label} (primary)"
        value = str(connection.pk)
        options.append(
            {
                "value": value,
                "label": label,
                "selected": value == selected if selected else is_primary,
            }
        )

    return options


def resolve_connection(pk: int, capability: str, *, access: ModelAccess) -> ResolvedModel:
    """Resolve `ModelConnection(pk=pk)` for `capability` -- the pk-addressed
    twin of `db_provider`'s role-keyed lookup, for a caller-supplied
    override rather than a durable role binding (e.g. the Ask-time
    model picker: the role binding stays the primary, this is a per-request
    substitute).

    Raises `ValueError` -- the same "nothing usable" signal
    `models.contracts.bindings.resolve()` and
    `models.contracts.engines.get_engine()` already raise, not a new
    exception type -- when: `pk` names no `ModelConnection` row, the
    connection's `capabilities` doesn't include `capability`, the
    connection's `engine` isn't a registered adapter
    (`models.contracts.engines.get_engine` raises this last case itself),
    or `access` does not allow `pk` (`resolve_connection_named` raises
    this last case, with a message naming the missing entitlement).

    A thin wrapper over `resolve_connection_named`, below, which does the
    actual lookup/validation and also hands back the connection's display
    name for callers (the Ask page's override path) that need both without
    a second query for the same row.
    """
    resolved, _name = resolve_connection_named(pk, capability, access=access)
    return resolved


def resolve_connection_named(pk: int, capability: str, *,
                             access: ModelAccess) -> tuple[ResolvedModel, str]:
    """`(resolved, display_name)` for `ModelConnection(pk=pk)` validated
    against `capability` and `access` -- the same lookup `resolve_connection`
    performs, paired with the connection's own `name` in the one query --
    avoiding a separate `connection_name(pk)` bare-name lookup that would
    re-fetch the row `resolve_connection` had just fetched, for the Ask
    page's "answered by {name}" line on the override path.

    Raises `ValueError` under the exact same conditions as
    `resolve_connection` -- see its docstring.
    """
    # THE GATE HALF, and it covers every submission path at once:
    # `agents.runtime.bindings.resolve_chat`, `tools.vision.views.
    # picked_connection`, `tools.vision.jobs`, `tools.rag.views.AskView`
    # and `tools.rag.jobs` all resolve a caller-supplied pk through here.
    #
    # The ROLE path (`db_provider`, `role_primary`) is deliberately NOT
    # gated -- see `models/README.md` and spec section 9.5: a set holding
    # the embedding connection must not break ingestion for the whole box.
    if not access.allows(pk):
        raise ValueError(
            f"Model connection {pk} needs an entitlement this account does not hold."
        )

    from models.registry.models import ModelConnection
    from models.contracts.engines import get_engine

    try:
        connection = ModelConnection.objects.get(pk=pk)
    except ModelConnection.DoesNotExist:
        raise ValueError(f"No connection resolved for pk {pk!r}") from None

    if capability not in connection.capabilities:
        raise ValueError(
            f"Connection {pk!r} does not support capability {capability!r}"
        )

    get_engine(connection.engine)  # raises ValueError for an unsupported engine

    return resolved_from_connection(connection), connection.name


def footprint_for(engine: str, endpoint: str, model_id: str) -> int | None:
    """The footprint (bytes) for `model_id` at `endpoint` on `engine` -- THE
    single path from a model ref to a footprint; the execution queue's
    future claim code has no other source for this fact.

    Matches on `engine` (exact) + `endpoint` (normalized with
    `models.registry.discovery.norm_endpoint` on BOTH sides -- the same
    trailing-slash-insensitive comparison `models/registry/views.py`'s
    health/in-use dedup already uses, so "http://x:11434" and
    "http://x:11434/" name the same connection here too) + `model_id`
    (exact -- unlike the catalog's bare/tagged merge, a `ModelConnection`
    row's `model_id` is registered verbatim, never normalized for this
    lookup).

    Exactly one match -> its `effective_footprint_bytes` (which may itself
    still be `None` -- a matched row can have neither fact set). Every
    OTHER case returns `None`, meaning "unknown -- the job runs alone":
    no matching row, more than one (an ambiguous ref must never silently
    pick one), or a `ProgrammingError`/`OperationalError` from the table not
    existing yet (mid-`migrate`) -- the same tolerance idiom
    `_bound_connection` above already uses.
    """
    from django.db import OperationalError, ProgrammingError

    from models.registry.discovery import norm_endpoint
    from models.registry.models import ModelConnection

    try:
        candidates = list(ModelConnection.objects.filter(engine=engine, model_id=model_id))
    except (ProgrammingError, OperationalError):
        return None

    endpoint_key = norm_endpoint(endpoint)
    matches = [c for c in candidates if norm_endpoint(c.endpoint) == endpoint_key]

    if len(matches) != 1:
        return None
    return matches[0].effective_footprint_bytes


def record_measured_footprint(engine: str, endpoint: str, model_id: str, size_bytes: int) -> None:
    """Persist `size_bytes` as the MEASURED footprint (rung 2) for the ONE
    `ModelConnection` matching `(engine, endpoint, model_id)` -- see the
    module docstring for why this uses `footprint_for`'s exact match rule,
    and `_record_footprint` below for the keep-the-maximum rule every
    write now obeys.
    """
    _record_footprint(
        engine, endpoint, model_id, size_bytes,
        bytes_field="measured_footprint_bytes", at_field="measured_footprint_at",
    )


def record_engine_reported_footprint(
    engine: str, endpoint: str, model_id: str, size_bytes: int,
) -> None:
    """Persist `size_bytes` as the ENGINE-REPORTED footprint (rung 3, spec
    §3.1) for the ONE matching `ModelConnection`.

    Called by the queue worker from inside the residency snapshot it is
    taking anyway (`models.queue.worker.Worker._residency_snapshot`) --
    never from a call made for this purpose. Obeys exactly the same
    opportunistic contract and the same keep-the-maximum rule as its
    rung-2 twin above, measured against rung 3's OWN standing value: the
    two columns are facts of different quality and never compare against
    each other.
    """
    _record_footprint(
        engine, endpoint, model_id, size_bytes,
        bytes_field="engine_reported_footprint_bytes",
        at_field="engine_reported_footprint_at",
    )


def _record_footprint(
    engine: str, endpoint: str, model_id: str, size_bytes: int, *,
    bytes_field: str, at_field: str,
) -> None:
    """THE ONE WRITER behind both recorders above.

    KEEP THE MAXIMUM (Q9, spec §3.2). No standing value -> write. A
    reading GREATER THAN OR EQUAL to the standing value -> write (a
    footprint going up is always believed; under-counting is the
    direction that crashes hosts). A reading BELOW it -> refuse
    entirely: not the bytes, not the timestamp, and one line records the
    connection, the standing value and the refused value.

    There is deliberately NO tolerance band. A percentage tolerance
    measured against the standing value ratchets geometrically -- five
    successive "within tolerance" 0.75x writes walk 26.4 GB down to 6.2
    GB and reproduce the exact shape this rule exists to refuse -- and
    the Q9 condition is RECURRING (a model that under-measures whenever
    it is warm), so repeated warm runs are the normal path, not an
    adversarial one. Keeping the maximum makes the standing value a
    high-water mark by construction, with no extra column and no constant
    to tune. The accepted cost -- a genuinely shrunk model stays high
    until an operator sets an override -- is the safe direction and is
    already the documented correction path.

    Opportunistic and silent-on-ambiguity in every other respect, exactly
    as before: never raises, no-ops on no match or an ambiguous match,
    tolerates a `ProgrammingError`/`OperationalError` from either the
    SELECT or the write, and tells no caller whether the write landed.
    """
    from django.db import OperationalError, ProgrammingError
    from django.utils import timezone

    from models.registry.discovery import norm_endpoint
    from models.registry.models import ModelConnection

    try:
        candidates = list(ModelConnection.objects.filter(engine=engine, model_id=model_id))
    except (ProgrammingError, OperationalError):
        return

    endpoint_key = norm_endpoint(endpoint)
    matches = [c for c in candidates if norm_endpoint(c.endpoint) == endpoint_key]
    if len(matches) != 1:
        return

    connection = matches[0]
    standing = getattr(connection, bytes_field)
    if standing is not None and size_bytes < standing:
        ratio = size_bytes / standing if standing else 1.0
        message = (
            "registry: refused to lower %s on connection %s (%r): standing %s bytes, "
            "refused reading %s bytes. A footprint is kept at its high-water mark; set "
            "footprint_override_bytes on this connection if the model really did get smaller"
        )
        args = (bytes_field, connection.pk, connection.name, standing, size_bytes)
        if ratio < FOOTPRINT_DIP_WARNING_RATIO:
            logger.warning(message, *args)
        else:
            logger.info(message, *args)
        return

    setattr(connection, bytes_field, size_bytes)
    setattr(connection, at_field, timezone.now())
    try:
        connection.save(update_fields=[bytes_field, at_field])
    except (ProgrammingError, OperationalError):
        return
