# Generated by Django 5.2.17 on 2026-08-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0004_seed_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='original_path',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
    ]
