# Generated by Django 5.2.17 on 2026-08-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0007_category_ci_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('connection_name', models.CharField(max_length=255)),
                ('model_id', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('citations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RagSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_limit', models.PositiveIntegerField(default=100)),
            ],
        ),
    ]
