# Generated by Django 5.2.4 on 2026-08-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0008_askrecord_ragsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='extraction',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='media_type',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=16),
        ),
        migrations.AddField(
            model_name='document',
            name='status_detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ragsettings',
            name='max_media_seconds',
            field=models.PositiveIntegerField(default=7200),
        ),
        migrations.AddField(
            model_name='ragsettings',
            name='max_upload_bytes',
            field=models.BigIntegerField(default=2147483648),
        ),
    ]
