# Generated by Django 5.2.17 on 2026-08-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0009_document_duration_seconds_document_extraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragsettings',
            name='max_document_pages',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
