# Generated by Django 5.2.17 on 2026-08-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0010_ragsettings_max_document_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragsettings',
            name='retrieval_top_k',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='ragsettings',
            name='retrieval_score_floor',
            field=models.FloatField(default=0.0),
        ),
    ]
