# Generated by Django 5.2.17 on 2026-08-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0011_ragsettings_retrieval_top_k_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragsettings',
            name='hybrid_search',
            field=models.BooleanField(default=False),
        ),
    ]
