# Generated by Django 5.2.4 on 2026-08-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0013_retire_chat_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='askrecord',
            name='owner_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='askrecord',
            name='owner_kind',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='askrecord',
            index=models.Index(fields=['owner_kind', 'owner_key'], name='rag_askrecord_owner'),
        ),
    ]
