# Generated by Django 5.2.4 on 2026-08-31 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """IA-2 T9: `DocumentEntitlement` -- the rag column's own label table,
    joining a `Document` to an `identity.Entitlement` by string FK (import
    law rule 4: `identity/` may not import `tools/`, so the reference runs
    the other way). One row per (document, entitlement) pair, OR-matched
    at read time by `tools.rag.access.readable_documents`."""

    dependencies = [
        ('identity', '0003_entitlement_and_grant'),
        ('rag', '0014_askrecord_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelled_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_labels', to='rag.document')),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_labels', to='identity.entitlement')),
                ('labelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entitlement'], name='rag_doclabel_entitlement')],
                'constraints': [models.UniqueConstraint(fields=('document', 'entitlement'), name='uniq_document_entitlement')],
            },
        ),
    ]
