# Generated by Django 5.2.4 on 2026-09-04, hand-arranged (see docstring below).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """`Document.workstream`/`Document.origin` (containment + provenance,
    owner decision 4 / author decision 12) and `WorkstreamPin` (the
    `tools/rag` half of the workstream join table -- see that model's own
    docstring for why it lives here and not in `agents`). No data
    migration: `workstream` is nullable and `origin` defaults to
    `upload`, true of every existing row without a back-fill.

    HAND-ARRANGED, NOT THE RAW AUTODETECTOR OUTPUT, for the same reason
    `agents/0006_workstream.py` was: the raw `makemigrations` output
    split `WorkstreamPin`'s three foreign keys off into separate
    `AddField` operations after a bare `CreateModel(id, pinned_at)`,
    because the autodetector defers a new model's FK fields whenever one
    of them targets a model this same migration also touches (`document`,
    via `AddField`/`AddIndex` above) -- exactly the mechanical split that
    migration's own docstring documents, just triggered by a different
    field. That split changes nothing about the resulting schema, so it
    is undone here: `WorkstreamPin` is created once, all three foreign
    keys and its `Meta` (ordering, the unique constraint, the index)
    inline -- the same shape `0015_documententitlement.py` already uses
    for `DocumentEntitlement`.

    NO `AlterModelOptions` OPERATION, though this is `Document`'s first
    `Meta` ever: the only option added is `indexes`, and `indexes` (like
    `constraints`) is deliberately excluded from Django's own
    `AlterModelOptions.ALTER_OPTION_KEYS` -- an index is its own
    `AddIndex` operation, never folded into an options diff. Confirmed
    against a real `makemigrations rag --name document_workstream_and_
    pins`, which produced the four `Document` operations below (matching
    this file except for the `WorkstreamPin` split just described) and no
    `AlterModelOptions`. Verified twice: `manage.py makemigrations
    --check --dry-run` exits 0 against this file, and `manage.py migrate`
    against the private DB (`farabunker_impl`) applies it cleanly.
    """

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0006_workstream'),
        ('rag', '0015_documententitlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='origin',
            field=models.CharField(choices=[('upload', 'Uploaded'), ('notes', 'Consolidated notes')], default='upload', max_length=16),
        ),
        migrations.AddField(
            model_name='document',
            name='workstream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='agents.workstream'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workstream'], name='rag_document_ws'),
        ),
        migrations.CreateModel(
            name='WorkstreamPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('workstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='agents.workstream')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstream_pins', to='rag.document')),
                ('pinned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned_at'],
                'indexes': [models.Index(fields=['document'], name='rag_wspin_document')],
                'constraints': [models.UniqueConstraint(fields=('workstream', 'document'), name='uniq_workstream_pin')],
            },
        ),
    ]
