# Generated by Django 5.2.4 on 2026-09-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_workstream_taint'),
        ('rag', '0016_document_workstream_and_pins'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='notes_conversation_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('notes_conversation_id__isnull', False)), fields=('notes_conversation_id',), name='uniq_notes_per_conversation'),
        ),
    ]
