# Generated by Django 5.2.4 on 2026-09-08 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Round 11 review I-5: a JUNCTION table for "what has this
    conversation attached", replacing a first cut (this same migration
    number, UNPUSHED, rewritten in place rather than superseded) that
    stored the claim as a single `Document.attached_conversation_id`
    column -- a shape that let a second conversation's re-upload of the
    same basename silently STEAL a document away from the first
    (`Document`'s own docstring, `tools/rag/models.py`, has the full
    reasoning). `unique_together` on (document, conversation_id) instead
    of that column's uniqueness-free shape: a re-upload from a second
    conversation now ADDS a row rather than overwriting one.

    THE FIRST CUT NEVER SHIPPED ANYWHERE (round 11 re-review, minor 3):
    it was applied to, and then rolled back off, this branch's OWN
    preview database within the same working session that authored it
    -- verified clean (no orphaned `rag_document.attached_conversation_
    id` column, no stray `django_migrations` row naming the old
    `0018_document_attached_conversation` file) before this rewrite was
    applied there. A DIFFERENT database that somehow already ran the
    first cut would be left with both: that orphaned column, AND a
    `django_migrations` row for a file that no longer exists on disk,
    alongside this migration applying cleanly under the new name --
    harmless to correctness, but worth a manual check (or a fresh
    database) before deploying this branch anywhere else the first cut
    might have run.
    """

    dependencies = [
        ('rag', '0017_document_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='rag.document')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('document', 'conversation_id'), name='uniq_document_attachment')],
            },
        ),
    ]
