# Generated by Django 5.2.4 on 2026-09-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    """Round 12 (owner ruling, verbatim: "if I submit a document but
    have scope for chat, then it should only be used in that chat...
    if I change the scope to workstream, it should be made available
    via the rag framework"). `Document.scope` (`"universal"` -- every
    existing row, no back-fill -- or `"conversation"`, chat-only,
    excluded from every corpus but its own conversation's) and
    `Document.owner_kind`/`owner_key` (`identity.access.owner_fields`'s
    own two-column shape, the SAME columns `AskRecord` already carries)
    -- who uploaded the row, the predicate a conversation-scoped
    document's visibility is judged by instead of entitlement labels.
    """

    dependencies = [
        ('agents', '0007_workstream_taint'),
        ('rag', '0018_documentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='owner_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='owner_kind',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='document',
            name='scope',
            field=models.CharField(choices=[('universal', 'Universal'), ('conversation', 'This chat only')], db_index=True, default='universal', max_length=16),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner_kind', 'owner_key'], name='rag_document_owner'),
        ),
    ]
