# Generated by Django 5.2.4 on 2026-09-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0019_document_scope_and_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentattachment',
            name='turn_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
