# Generated by Django 5.2.17 on 2026-09-10 03:09

from django.db import migrations


class Migration(migrations.Migration):
    """C-42: `Category.description` was declared in 0003 and never reached
    production -- this app has no `forms.py` and no `admin.py`, no template
    renders it, and the seed migration (`0004_seed_default_categories.py`)
    passes `name` only. Its only touches were in the tests written for the
    field itself. A column nothing sets or reads is a column nothing can be
    trusted to have, so it goes."""

    dependencies = [
        ('rag', '0020_documentattachment_turn_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
